name: Daily ETLs

on:
  schedule:
  - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  etls:
    runs-on: ubuntu-latest
    env:
      MONGO_SERVER: ${{ secrets.MONGO_SERVER }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          echo "test $MONGO_SERVER"
          python -m pip install -r requirements.txt


      - name: Chargers ETL
        run: |
          python -m scripts.extract_chargers

      - name: Tariffs ETL
        run: |
          python -m scripts.extract_tariffs
